name = "rolldoradoapp-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldoradoapp.pt"
HMAC_KEY = "ae9dc3238d5c96c118987bd05acdd9073b5795dfff434e2d89c2af53176c09ad"
COOKIE_NAME = "kah"
PLAY_PATH = "start"
BUTTON_ID = "p688eb73dcd9bbb341f6d21bc438d793f"
GATE_SALT = "5d1a7cea6811080c"
