name = "rolldoradoapp-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldoradoapp.pt"
HMAC_KEY = "ae9dc3238d5c96c118987bd05acdd9073b5795dfff434e2d89c2af53176c09ad"
COOKIE_NAME = "4jn"
PLAY_PATH = "start-now"
BUTTON_ID = "p688eb73dcd9bbb341f6d21bc438d793f"
GATE_SALT = "92d19e130fbbd5da"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "4l6d"
CTA_SELECTOR = ".play-button"
